apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: lldap
          image: docker pull ghcr.io/lldap/lldap:v0.6.2-alpine-rootless
          ports:
            - name: ldap
              containerPort: 3890
            - name: http
              containerPort: 17170
          envFrom:
            - secretRef:
                name: lldap-secrets
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"

            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-app
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-lldap-role
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-lldap-role
                  key: password
            - name: DB_NAME
              value: "lldap" # The database name you declared
            - name: LLDAP_DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST).$(K8S_NAMESPACE):$(DB_PORT)/$(DB_NAME)"
            - name: LLDAP_LDAP_BASE_DN
              value: "dc=rbn,dc=is"
            - name: LLDAP_HTTP_URL #TODO
              value: "https://auth.rbn.is"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: lldap-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: lldap-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
