apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds.yaml
  - kured.yaml
  - cilium.yaml
  - gateway-api.yaml
  - external-secrets.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - kaniop.yaml
