apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - listenerpolicy.yaml

patches:
  - target:
      kind: Gateway
    patch: |
      - op: add
        path: /spec/gatewayClassName
        value: kgateway
