apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: HelmRelease
      name: cilium
    patch: |
      - op: add
        path: /spec/values/gatewayAPI/enabled
        value: true
      - op: add
        path: /spec/values/gatewayAPI/enableAlpn
        value: true
