apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator-repo
spec:
  interval: 24h
  ref:
    tag: v0.89.0
  url: https://github.com/prometheus-operator/prometheus-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crd
spec:
  interval: 10m
  path: ./example/prometheus-operator-crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator-repo
