apiVersion: apps/v1
kind: Deployment
metadata:
  name: handlich
  labels:
    app.kubernetes.io/name: handlich
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: handlich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: handlich
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: handlich
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      automountServiceAccountToken: false
      containers:
        - name: handlich
          image: ghcr.io/rbnis/handlich:0.1.3
          imagePullPolicy: IfNotPresent
          args: ["--config", "/config/config.yaml"]
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          resources:
            requests:
              cpu: 25m
              memory: 20Mi
            limits:
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
      volumes:
        - name: config
          configMap:
            name: handlich
      tolerations: []
