apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity-provider

resources:
  - namespace.yaml
  - passwordgenerator.yaml
  - postgresrolesecret.yaml
  - postgrescluster.yaml
  - lldap
  - authelia
