apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: helmrelease.yaml
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels/gateway.k8s.rbn.is~1attach-route
        value: "true"
