apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - listenerset.yaml
  - tlsroute.yaml

patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels/gateway.k8s.rbn.is~1attach-listener
        value: "true"
